services:
  auth_db:
    container_name: auth_db
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth_db
    volumes:
      - data:/var/lib/postgresql/data
      - ./storage/task-auth-init.sql:/docker-entrypoint-initdb.d/task-auth-init.sql
    ports:
      - "5432:5432"
    networks:
      - app_network

  auth_app:
    build: .
    depends_on:
      - auth_db
    container_name: auth_app
    volumes:
      - ./config/config.yaml:/root/config.yaml
    ports:
      - "4040:4040"
    networks:
      - app_network

volumes:
  data:

networks:
  app_network:
    driver: bridge